package com.github.bjlhx15.mybatis.readwrite.split.model.auto;

public class AccountBalance {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accountbalance.id
     *
     * @mbg.generated Sat Jul 27 13:12:01 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accountbalance.name
     *
     * @mbg.generated Sat Jul 27 13:12:01 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accountbalance.version
     *
     * @mbg.generated Sat Jul 27 13:12:01 CST 2019
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accountbalance.balance
     *
     * @mbg.generated Sat Jul 27 13:12:01 CST 2019
     */
    private Integer balance;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accountbalance.id
     *
     * @return the value of accountbalance.id
     *
     * @mbg.generated Sat Jul 27 13:12:01 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accountbalance.id
     *
     * @param id the value for accountbalance.id
     *
     * @mbg.generated Sat Jul 27 13:12:01 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accountbalance.name
     *
     * @return the value of accountbalance.name
     *
     * @mbg.generated Sat Jul 27 13:12:01 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accountbalance.name
     *
     * @param name the value for accountbalance.name
     *
     * @mbg.generated Sat Jul 27 13:12:01 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accountbalance.version
     *
     * @return the value of accountbalance.version
     *
     * @mbg.generated Sat Jul 27 13:12:01 CST 2019
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accountbalance.version
     *
     * @param version the value for accountbalance.version
     *
     * @mbg.generated Sat Jul 27 13:12:01 CST 2019
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accountbalance.balance
     *
     * @return the value of accountbalance.balance
     *
     * @mbg.generated Sat Jul 27 13:12:01 CST 2019
     */
    public Integer getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accountbalance.balance
     *
     * @param balance the value for accountbalance.balance
     *
     * @mbg.generated Sat Jul 27 13:12:01 CST 2019
     */
    public void setBalance(Integer balance) {
        this.balance = balance;
    }
}