package com.github.bjlhx15.mybatis.readwrite.split.repository.auto;

import com.github.bjlhx15.mybatis.readwrite.split.model.auto.AccountBalance;
import com.github.bjlhx15.mybatis.readwrite.split.model.auto.AccountBalanceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AccountBalanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accountbalance
     *
     * @mbg.generated Sat Jul 27 13:12:01 CST 2019
     */
    long countByExample(AccountBalanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accountbalance
     *
     * @mbg.generated Sat Jul 27 13:12:01 CST 2019
     */
    int deleteByExample(AccountBalanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accountbalance
     *
     * @mbg.generated Sat Jul 27 13:12:01 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accountbalance
     *
     * @mbg.generated Sat Jul 27 13:12:01 CST 2019
     */
    int insert(AccountBalance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accountbalance
     *
     * @mbg.generated Sat Jul 27 13:12:01 CST 2019
     */
    int insertSelective(AccountBalance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accountbalance
     *
     * @mbg.generated Sat Jul 27 13:12:01 CST 2019
     */
    List<AccountBalance> selectByExample(AccountBalanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accountbalance
     *
     * @mbg.generated Sat Jul 27 13:12:01 CST 2019
     */
    AccountBalance selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accountbalance
     *
     * @mbg.generated Sat Jul 27 13:12:01 CST 2019
     */
    int updateByExampleSelective(@Param("record") AccountBalance record, @Param("example") AccountBalanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accountbalance
     *
     * @mbg.generated Sat Jul 27 13:12:01 CST 2019
     */
    int updateByExample(@Param("record") AccountBalance record, @Param("example") AccountBalanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accountbalance
     *
     * @mbg.generated Sat Jul 27 13:12:01 CST 2019
     */
    int updateByPrimaryKeySelective(AccountBalance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accountbalance
     *
     * @mbg.generated Sat Jul 27 13:12:01 CST 2019
     */
    int updateByPrimaryKey(AccountBalance record);
}